<?php View::content(); ?>
<h2>Editar categoría #<?= $categoria->id; ?></h2>
<?= Form::open(); ?>
<?= Form::label('Nombre', 'categoria.nombre'); ?>
<?= Form::text('categoria.nombre', 'class="form-control"'); ?>
<?= Form::label('Slug', 'categoria.slug'); ?>
<?= Form::text('categoria.slug', 'class="form-control"'); ?>
<?= Form::label('Descripción', 'categoria.descripcion'); ?>
<?= Form::textarea('categoria.descripcion', 'class="form-control"'); ?>
<?= Form::label('Orden', 'categoria.orden'); ?>
<?= Form::text('categoria.orden', 'class="form-control"'); ?>
<?= Form::hidden('categoria.id'); ?>
<?= Form::label('Activa', 'categoria.activa'); ?>
<?= Form::select('categoria.activa', array('0' => 'No', '1' => 'Sí'), 'class="form-control input-sm"'); ?>
<?= Form::label('Visible', 'categoria.visible'); ?>
<?= Form::select('categoria.visible', array('0' => 'No', '1' => 'Sí'), 'class="form-control input-sm"'); ?>
<br />
<?= Form::submit('Actualizar', 'class="btn btn-success"'); ?>&nbsp;
<?= Html::linkAction('index', 'Volver', 'class="btn btn-default"'); ?>
<?= Form::close(); ?>
