<!-- Modal -->
<div class="modal fade" id="portadaModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Seleccion de imagen de portada</h4>
            </div>
            <div class="modal-body">
                <?php foreach ((new Imagen)->activas() as $img): ?>
                    <div class="media">
                        <div class="media-left">
                            <?= Html::img('upload/' . $img->archivo, '', 'class="thumbnail" width="64px"'); ?>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">Media heading</h4>
                            <button class="btn btn-default btn-sm"><i class="fa fa-copy"></i></button>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
