<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
       aria-expanded="false"><?= $name; ?> <i class="fa fa-caret-down"></i></a>
    <ul class="dropdown-menu" role="menu">
        <?php foreach ($items as $item): ?>
            <li>
                <?= Html::link($item->url, $item->nombre); ?>    
            </li>
        <?php endforeach; ?>
    </ul>
</li>
